#!/usr/bin/env python3
"""Bounded, resumable local Claude -> gates -> Codex -> Claude milestone sequence.

Drives the milestones in agent/milestones.py in order. Each milestone is its
own bounded implement/gate/review/fix cycle; a PASS checkpoints (local commit
only, never pushed) and the controller continues automatically to the next
milestone. A milestone whose required_env is missing is marked blocked and
skipped so independent milestones can still proceed; an exhausted repair/
review budget or the stop file/timeout stops the whole run for diagnosis.
Progress is recorded in agent/runs/milestones-state.json so a later
invocation resumes instead of restarting.
"""
import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path
import signal
import subprocess
import sys
import time

import milestones

ROOT = Path(__file__).resolve().parents[1]
STATE_PATH = ROOT / 'agent/runs/milestones-state.json'
API_CONFIG_PATH = 'app/src/main/java/com/example/eso1/data/auth/ApiConfig.kt'
CREDENTIAL_PREFIXES = ('.env', 'local.properties')
CREDENTIAL_SUFFIXES = ('.jks', '.keystore')

SCHEMA = {"type": "object", "properties": {
    "verdict": {"type": "string", "enum": ["PASS", "FIX", "BLOCKED"]},
    "summary": {"type": "string"},
    "findings": {"type": "array", "items": {"type": "string"}},
    "visual_reviewed": {"type": "boolean"}},
    "required": ["verdict", "summary", "findings", "visual_reviewed"], "additionalProperties": False}


class StopRequested(RuntimeError):
    """Stop file or overall runtime deadline; never silently swallowed or retried."""


class ScopeViolation(RuntimeError):
    """Claude touched a forbidden path or git state changed unexpectedly; left uncommitted for inspection."""


def validate_review(value):
    if set(value) != set(SCHEMA['required']):
        raise RuntimeError('Malformed review fields')
    if value['verdict'] not in ('PASS', 'FIX', 'BLOCKED') or type(value['visual_reviewed']) is not bool:
        raise RuntimeError('Malformed review verdict')
    if not isinstance(value['summary'], str) or not isinstance(value['findings'], list) or not all(isinstance(x, str) for x in value['findings']):
        raise RuntimeError('Malformed review content')
    if value['verdict'] == 'PASS' and (value['findings'] or not value['visual_reviewed']):
        raise RuntimeError('PASS requires visual inspection and no unresolved findings')
    if value['verdict'] == 'FIX' and not value['findings']:
        raise RuntimeError('FIX requires actionable findings')
    return value


def allowed_path(path, extra=()):
    if path in extra:
        return True
    return path.startswith(('app/src/main/', 'app/src/test/', 'app/src/androidTest/'))


CONTROLLER_OWNED_PATHS = ('agent/CURRENT_TASK.md', API_CONFIG_PATH, 'docs/decisions/3D_ENGINE_EVALUATION.md')

# Named gradle/build files a milestone may be granted explicit, individual write access
# to via Milestone.extra_paths. Globs (wrapper binary/scripts) are never lifted, even then.
GRADLE_NAMED_FILES = (
    'build.gradle.kts', 'app/build.gradle.kts', 'settings.gradle.kts', 'gradle.properties',
    'gradle/libs.versions.toml', 'gradle/gradle-daemon-jvm.properties',
)
GRADLE_ALWAYS_PROTECTED_GLOBS = ('gradlew*', 'gradle/wrapper/**')


def checkpoint_allowed(path, extra=()):
    if path.startswith(CREDENTIAL_PREFIXES) or path.endswith(CREDENTIAL_SUFFIXES):
        return False
    return allowed_path(path, extra) or path in CONTROLLER_OWNED_PATHS


def snapshot():
    paths = subprocess.check_output(['git', 'ls-files', '-z', '--cached', '--others', '--exclude-standard'], cwd=ROOT).decode().split('\0')
    result = {}
    for name in paths:
        if name:
            p = ROOT / name
            if p.is_symlink():
                raise RuntimeError('Symlink in project: ' + name)
            result[name] = hashlib.sha256(p.read_bytes()).hexdigest() if p.is_file() else 'MISSING'
    return result


def load_state(restart):
    if restart or not STATE_PATH.exists():
        return {}
    try:
        return json.loads(STATE_PATH.read_text())
    except (json.JSONDecodeError, OSError):
        return {}


def missing_env(milestone):
    return [v for v in milestone.required_env if not os.environ.get(v)]


def api_config_kt(base_url):
    escaped = base_url.replace('\\', '\\\\').replace('"', '\\"')
    return (
        '// Generated by agent/loop.py from the FEELY_API_BASE environment value.\n'
        '// Do not hand-edit; rerunning the controller overwrites this file.\n'
        'package com.example.eso1.data.auth\n\n'
        'object ApiConfig {\n'
        f'    const val BASE_URL: String = "{escaped}"\n'
        '}\n'
    )


class Loop:
    def __init__(self, args):
        self.args = args
        self.deadline = time.monotonic() + args.minutes * 60
        self.run = ROOT / 'agent/runs' / time.strftime('%Y%m%d-%H%M%S')
        self.run.mkdir(parents=True, exist_ok=False)
        self.env = os.environ.copy()
        self.env.setdefault('JAVA_HOME', '/Applications/Android Studio.app/Contents/jbr/Contents/Home')
        self.env['ANDROID_SERIAL'] = args.serial
        self.env['PATH'] = str(Path.home() / '.local/bin') + ':' + self.env['PATH']
        # Two separately-named trackers over the same kind of snapshot, intentionally not
        # shared: scope_baseline is what verify_scope() diffs against to catch the Claude
        # subprocess touching a forbidden path; checkpoint_baseline is what checkpoint()
        # diffs against to decide what to `git add`. write_controlled() must not update
        # either — a controller-written file (CURRENT_TASK.md, the engine decision doc,
        # ApiConfig.kt) needs to show up as "changed" to checkpoint() so it actually gets
        # committed, while verify_scope() ignores those specific paths outright (see
        # CONTROLLER_OWNED_PATHS) rather than by making them look unchanged.
        initial = snapshot()
        self.scope_baseline = initial
        self.checkpoint_baseline = initial
        self.head = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT)
        self.schema = self.run / 'review-schema.json'
        self.schema.write_text(json.dumps(SCHEMA))
        self.state = load_state(args.restart)
        self.current_milestone = None

    def save_state(self):
        STATE_PATH.write_text(json.dumps(self.state, indent=2))

    def check_stop(self):
        if (ROOT / 'agent/STOP').exists():
            raise StopRequested('Stop file detected')
        if time.monotonic() >= self.deadline:
            raise StopRequested('Total runtime limit reached')

    def command(self, argv, label, timeout=600, stdin=None):
        self.check_stop()
        self.log('START ' + label)
        with (self.run / (label + '.log')).open('w') as out:
            process = subprocess.Popen(argv, cwd=ROOT, env=self.env, stdin=subprocess.PIPE if stdin else subprocess.DEVNULL,
                                       stdout=out, stderr=subprocess.STDOUT, start_new_session=True)
            try:
                if stdin:
                    process.stdin.write(stdin.encode()); process.stdin.close()
                end = time.monotonic() + timeout
                while process.poll() is None:
                    self.check_stop()
                    if time.monotonic() >= end:
                        raise RuntimeError(label + ' timed out')
                    time.sleep(1)
                if process.returncode:
                    raise RuntimeError(label + ' failed; see ' + str(self.run / (label + '.log')))
            finally:
                if process.poll() is None:
                    os.killpg(process.pid, signal.SIGTERM)
                    try:
                        process.wait(timeout=5)
                    except subprocess.TimeoutExpired:
                        os.killpg(process.pid, signal.SIGKILL); process.wait()
        self.log('DONE ' + label)

    def log(self, text):
        line = time.strftime('%Y-%m-%d %H:%M:%S') + ' ' + text
        print(line, flush=True)
        with (self.run / 'RUN_LOG.md').open('a') as out:
            out.write(line + '\n')

    def write_controlled(self, rel_path, content):
        """Write a controller-owned file (acceptance criteria, generated config, the
        engine decision doc). Deliberately does not touch scope_baseline or
        checkpoint_baseline — see the comment in __init__ for why."""
        path = ROOT / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    def verify_scope(self, extra_paths=()):
        current = snapshot()
        changed = [p for p in set(self.scope_baseline) | set(current) if self.scope_baseline.get(p) != current.get(p)]
        changed = [p for p in changed if p not in CONTROLLER_OWNED_PATHS]
        forbidden = [p for p in changed if not allowed_path(p, extra_paths)]
        if forbidden:
            raise ScopeViolation('Protected files changed: ' + ', '.join(forbidden))
        if subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT) != self.head:
            raise ScopeViolation('Git HEAD changed unexpectedly')
        if subprocess.check_output(['git', 'diff', '--cached', '--name-only'], cwd=ROOT).strip():
            raise ScopeViolation('Unexpected index changes')

    def checkpoint(self, message, extra_paths=()):
        """Local-only commit of the current controller-owned + allowed app changes.
        Never pushes. Returns the new commit hash, or None if nothing changed."""
        current = snapshot()
        changed = sorted(p for p in set(current) | set(self.checkpoint_baseline) if self.checkpoint_baseline.get(p) != current.get(p))
        stage = [p for p in changed if checkpoint_allowed(p, extra_paths)]
        if not stage:
            return None
        subprocess.check_output(['git', 'add', '--'] + stage, cwd=ROOT)
        subprocess.check_output(['git', 'commit', '-m', message], cwd=ROOT)
        fresh = snapshot()
        self.scope_baseline = fresh
        self.checkpoint_baseline = fresh
        self.head = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT)
        return self.head.decode().strip()

    def checkpoint_wip(self):
        if not self.current_milestone:
            return None
        extra = milestones.MILESTONES_BY_KEY[self.current_milestone].extra_paths
        self.state[self.current_milestone] = 'in_progress'
        self.save_state()
        return self.checkpoint(f'WIP checkpoint: {self.current_milestone} interrupted (not reviewed/passed)', extra)

    def claude(self, prompt, label, readonly=False, extra_paths=()):
        tools = 'Read,Glob,Grep' if readonly else 'Read,Glob,Grep,Edit,Write'
        deny = [
            'Read(.env*)', 'Read(local.properties)', 'Read(**/*.jks)', 'Read(**/*.keystore)',
            'Edit(agent/**)', 'Write(agent/**)', 'Edit(docs/**)', 'Write(docs/**)',
            'Edit(AGENTS.md)', 'Write(AGENTS.md)', 'Edit(CLAUDE.md)', 'Write(CLAUDE.md)',
            'Edit(.git/**)', 'Write(.git/**)']
        # Gradle/build files stay denied by name; a milestone's extra_paths can lift the
        # deny for the exact named files it was explicitly scoped to touch (never a glob,
        # and never the wrapper itself) — verify_scope() still rejects anything else.
        for pattern in GRADLE_NAMED_FILES:
            if pattern not in extra_paths:
                deny += [f'Edit({pattern})', f'Write({pattern})']
        for pattern in GRADLE_ALWAYS_PROTECTED_GLOBS:
            deny += [f'Edit({pattern})', f'Write({pattern})']
        # Restricted mode confines file tools to the workspace. No shell, plugins or MCP.
        settings = {'disableAllHooks': True, 'permissions': {'deny': deny}}
        argv = ['claude', '-p', prompt, '--restricted', '--safe-mode', '--permission-mode', 'dontAsk',
                '--permission-prompts', 'none', '--tools', tools, '--allowedTools', tools,
                '--strict-mcp-config', '--mcp-config', '{"mcpServers":{}}',
                '--settings', json.dumps(settings), '--no-session-persistence', '--output-format', 'json',
                '--max-budget-usd', str(self.args.claude_budget)]
        self.command(argv, label, timeout=900)
        response = json.loads((self.run / (label + '.log')).read_text())
        if response.get('is_error') or response.get('subtype') != 'success' or response.get('permission_denials'):
            raise RuntimeError('Claude failed or encountered denied permissions: ' + label)
        if 'BLOCKED' in response.get('result', ''):
            raise RuntimeError('Claude reported BLOCKED; inspect ' + label)
        self.verify_scope(extra_paths)
        return response.get('result', '')

    def gates(self, milestone, label):
        self.command(['git', 'diff', '--check'], f'{label}-diff')
        self.command(['./gradlew', '--no-daemon', 'assembleDebug', 'test', 'lintDebug', 'connectedDebugAndroidTest'], f'{label}-gradle', timeout=900)
        destination = self.run / f'{label}-visual'
        self.command([sys.executable, str(ROOT / 'agent/visual_qa.py'), '--serial', self.args.serial,
                      '--output', str(destination), '--milestone', milestone.visual_key,
                      '--themes', ','.join(milestone.themes), '--languages', ','.join(milestone.languages)],
                     f'{label}-visual', timeout=900)  # theme x language x territory-interaction matrix is large
        images = sorted(destination.glob('*.png'))
        if not images:
            raise RuntimeError('No visual evidence produced for ' + label)
        return images

    def review(self, milestone, label, images):
        output = self.run / f'{label}-review.json'
        prompt = ('Read AGENTS.md, docs/PRODUCT_VISION.md, docs/LAUNCH_CRITERIA.md, agent/CURRENT_TASK.md. '
                  f'This is milestone "{milestone.key}" ({milestone.title}) of a multi-milestone build; '
                  'review only this milestone\'s bounded scope, not the full release. '
                  'Review the current diff and relevant source. Inspect every attached screenshot. '
                  f'This run evidence is at {self.run}. Build/test/lint and the scripted interaction journey succeeded. '
                  f'Read {destination_manifest(self.run, label)} for themes/languages covered and its not_verified list. '
                  'Check evidence logs and the visual manifest; do not infer untested configurations passed. '
                  'Return strict JSON for this milestone only. Do not execute Gradle or other agents. Do not modify files.')
        argv = ['codex', 'exec', '--ignore-user-config', '--ignore-rules', '--ephemeral',
                '--sandbox', 'read-only', '-c', 'approval_policy="never"', '--output-schema', str(self.schema),
                '--output-last-message', str(output)]
        for path in images:
            argv.extend(['--image', str(path)])
        argv.append(prompt)
        self.command(argv, f'{label}-codex', timeout=900)
        # Codex is read-only and writes nothing, but a prior Claude call in this same
        # milestone may legitimately have touched milestone.extra_paths (e.g. engine's
        # one Gradle dependency) — that diff is still outstanding until checkpoint(),
        # so verify_scope must be told about it here too or it misreads it as a violation.
        self.verify_scope(milestone.extra_paths)
        return validate_review(json.loads(output.read_text()))

    def write_launch_checklist(self):
        lines = [
            '# Launch status snapshot — controller-generated, not a release decision', '',
            "Generated by agent/loop.py from this run's recorded milestone outcomes. "
            'Missing evidence is reported as NOT VERIFIED, never as a pass. This file states gate '
            'status only; it does not claim owner endorsement, clinical effectiveness, or launch '
            'readiness (see docs/LAUNCH_CRITERIA.md).', '',
        ]
        for m in milestones.MILESTONES:
            status = self.state.get(m.key, 'not started')
            lines.append(f'- **{m.title}** (`{m.key}`): {status}')
        lines += [
            '',
            '## Known gaps carried from docs/AUTH_INTEGRATION.md and docs/LAUNCH_CRITERIA.md', '',
            '- Live reachability of the FeelY API base was not independently verified in automation '
            '(a prior manual check returned HTTP 403 / error 1010).',
            '- Backend-side AGB access enforcement and recording of the presented language are '
            'owner-reported, not independently confirmed in this preparation cycle.',
            '- Email delivery, password-reset delivery, and Google Android client configuration '
            'remain unverified.',
            '- Content-sourcing review for factual explanatory copy is tracked in each milestone\'s '
            'implement/fix logs under this run directory, not merged into docs/ automatically.',
            '- No public release, store listing, signing, or payment flow is in scope here.', '',
        ]
        (self.run / 'LAUNCH_CHECKLIST.md').write_text('\n'.join(lines))

    def run_milestone(self, milestone):
        self.current_milestone = milestone.key
        extra = milestone.extra_paths
        self.log('MILESTONE START ' + milestone.key)
        context = 'Read CLAUDE.md, docs/PRODUCT_VISION.md, docs/LAUNCH_CRITERIA.md, agent/CURRENT_TASK.md. '
        if milestone.design_brief:
            self.write_controlled('agent/CURRENT_TASK.md', milestone.design_brief.rstrip() + '\n')
            recommendation = self.claude(
                context + 'Produce your recommendation as this response\'s final text; you cannot write files '
                'in this read-only phase.', milestone.key + '-design', readonly=True)
            self.write_controlled(
                'docs/decisions/3D_ENGINE_EVALUATION.md',
                '# 3D engine evaluation — ' + time.strftime('%Y-%m-%d') + '\n\n'
                'Captured verbatim from the design-phase agent response below. This is a working '
                'recommendation for the controller to act on next, not an owner-approved architecture '
                'decision or a claim that the chosen approach has been benchmarked on real hardware.\n\n'
                '---\n\n' + recommendation.strip() + '\n')
        self.write_controlled('agent/CURRENT_TASK.md', milestone.full_brief())
        if milestone.key == 'account':
            self.write_controlled(API_CONFIG_PATH, api_config_kt(os.environ['FEELY_API_BASE']))
        if not milestone.controller_only:
            self.claude(context + 'Implement the current task. The orchestrator runs checks after you finish. '
                        'Only edit app source/resources/tests' + (' plus the exact extra files named in your '
                        'task brief' if extra else '') + '. Report BLOCKED if needed.',
                        milestone.key + '-implement', extra_paths=extra)
        build_attempts = 0
        review_round = 0
        attempt = 0
        while True:
            attempt += 1
            label = f'{milestone.key}-{attempt}'
            try:
                images = self.gates(milestone, label)
            except StopRequested:
                raise
            except ScopeViolation:
                raise
            except Exception as exc:
                build_attempts += 1
                if build_attempts > self.args.max_build_repairs:
                    raise RuntimeError(f'{milestone.key}: build/test/lint/visual repair limit reached: {exc}')
                self.log(f'GATE FAILURE {milestone.key}: {exc}')
                self.claude(context + f'Build, test, lint, or the scripted interaction journey failed: {exc}. '
                            'Fix the underlying problem; stay within the current task.', f'{label}-buildfix',
                            extra_paths=extra)
                continue
            if milestone.key == 'release':
                self.write_launch_checklist()
            review_round += 1
            review = self.review(milestone, label, images)
            self.log('REVIEW ' + review['verdict'] + ' (' + milestone.key + ')')
            if review['verdict'] == 'BLOCKED':
                raise RuntimeError(milestone.key + ': ' + review['summary'])
            if review['verdict'] == 'PASS':
                self.claude(context + 'Codex passed this milestone. Read ' + str(self.run / f'{label}-review.json') +
                            '. Give a concise completion handoff. Do not edit files or begin another milestone.',
                            f'{milestone.key}-handoff', readonly=True, extra_paths=extra)
                # Checkpoint before recording 'passed': if the commit fails for any reason,
                # the milestone must not be marked done over an uncommitted tree — the next
                # resume should retry it, not skip it.
                commit = self.checkpoint(f'Milestone {milestone.key} passed', extra)
                self.state[milestone.key] = 'passed'
                self.save_state()
                self.log('MILESTONE PASS ' + milestone.key + (' commit ' + commit if commit else ' (nothing to commit)'))
                return
            if review_round >= self.args.max_reviews:
                raise RuntimeError(milestone.key + ': review retry limit reached')
            self.claude(context + 'Fix valid findings from ' + str(self.run / f'{label}-review.json') +
                        '. Stay within current task; explain evidence for disagreements.', f'{label}-fix',
                        extra_paths=extra)

    def execute(self):
        blocked = {}
        for milestone in milestones.MILESTONES:
            if self.state.get(milestone.key) == 'passed':
                continue
            missing = missing_env(milestone)
            if missing:
                reason = 'missing env: ' + ','.join(missing)
                self.state[milestone.key] = 'blocked: ' + reason
                self.save_state()
                self.log('MILESTONE BLOCKED ' + milestone.key + ' (' + reason + ')')
                blocked[milestone.key] = reason
                continue
            self.run_milestone(milestone)
        if blocked:
            self.log('RUN COMPLETE WITH BLOCKED MILESTONES: ' + ', '.join(f'{k} ({v})' for k, v in blocked.items()))
        else:
            self.log('RUN COMPLETE — ALL MILESTONES PASSED')


def destination_manifest(run, label):
    return str(run / f'{label}-visual' / 'manifest.json')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--serial', required=True, help='Explicit emulator serial; physical devices are refused')
    parser.add_argument('--max-reviews', type=int, default=3, choices=range(1, 4), help='Codex review rounds per milestone')
    parser.add_argument('--max-build-repairs', type=int, default=2, choices=range(1, 4), help='Build/test/lint/visual repair attempts per milestone')
    parser.add_argument('--minutes', type=int, default=180, choices=range(1, 481), help='Overall runtime limit for this invocation; hitting it stops cleanly and resumes next run')
    parser.add_argument('--claude-budget', type=float, default=3.0, help='Per-invocation USD cap, not a combined provider cap')
    parser.add_argument('--restart', action='store_true', help='Discard saved milestone progress and start the sequence over (does not discard committed app code)')
    args = parser.parse_args()
    if not args.serial.startswith('emulator-') or not 0 < args.claude_budget <= 10:
        parser.error('Use an emulator serial and Claude budget between 0 and 10')
    if subprocess.check_output(['git', 'branch', '--show-current'], cwd=ROOT).decode().strip() != 'agent/autonomous-dev':
        parser.error('Expected agent/autonomous-dev branch')
    if subprocess.check_output(['git', 'status', '--porcelain'], cwd=ROOT).strip():
        parser.error('Start from a clean committed working tree')
    (ROOT / 'agent/runs').mkdir(exist_ok=True)
    with (ROOT / 'agent/runs/loop.lock').open('w') as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            parser.error('Another loop is running')
        loop = Loop(args)
        try:
            loop.execute()
        except ScopeViolation as exc:
            loop.log('STOP (left uncommitted for inspection): ' + str(exc))
            return 1
        except (Exception, KeyboardInterrupt) as exc:
            loop.log('STOP: ' + str(exc))
            try:
                commit = loop.checkpoint_wip()
                if commit:
                    loop.log('WIP checkpoint committed: ' + commit)
            except Exception as checkpoint_exc:
                loop.log('WIP checkpoint failed: ' + str(checkpoint_exc))
            return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
